# Generated by Django 3.1.2 on 2021-03-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'permissions': (('attachments.add_attachments', 'Can add attachment'), ('attachments.delete_attachments', 'Can delete attachment'), ('attachments.delete_foreign_attachments', 'Can delete foreign attachments'))},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
