# Generated by Django 2.2.5 on 2019-12-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='title',
            field=models.CharField(default='blog_related', max_length=100),
            preserve_default=False,
        ),
    ]
