# Generated by Django 3.1.1 on 2020-10-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191229_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='City',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='query',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='query',
            name='Last_name',
        ),
        migrations.AddField(
            model_name='query',
            name='Email_id',
            field=models.EmailField(default=None, max_length=50),
        ),
    ]
