# Generated by Django 3.1.1 on 2020-10-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201020_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='First_name',
            field=models.CharField(max_length=100),
        ),
    ]
