# Generated by Django 3.1.1 on 2020-10-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201020_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Email',
            field=models.EmailField(default='tarunmzn98@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
