# Generated by Django 3.1.1 on 2020-10-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_query_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='City',
        ),
        migrations.RemoveField(
            model_name='query',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='query',
            name='Last_name',
        ),
    ]
