# Generated by Django 3.1.1 on 2020-10-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201020_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Email_id',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
