# Generated by Django 3.1.1 on 2020-10-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_query_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='Subject',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='Email_id',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='First_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='title',
            new_name='Title',
        ),
    ]
