# Generated by Django 3.1.1 on 2020-10-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201021_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Email',
            field=models.EmailField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
